package net.minidev.json.parser;

/*
 *    Copyright 2011 JSON-SMART authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UnsupportedEncodingException;

/**
 * Parser for JSON text. Please note that JSONParser is NOT thread-safe.
 * 
 * @author Uriel Chemouni <uchemouni@gmail.com>
 */
class JSONParserInputStream extends JSONParserReader {
	// len
	public JSONParserInputStream(int permissiveMode) {
		super(permissiveMode);
	}

	/**
	 * use to return Primitive Type, or String, Or JsonObject or JsonArray
	 * generated by a ContainerFactory
	 */
	public Object parse(InputStream in) throws ParseException {
		return parse(in, ContainerFactory.FACTORY_SIMPLE, ContentHandlerDumy.HANDLER);
	}
	
	/**
    * use to return Primitive Type, or String, Or JsonObject or JsonArray
    * generated by a ContainerFactory
    * 
	 * @throws UnsupportedEncodingException If the named charset is not supported by an InputStreamReader
    */
   public Object parse(InputStream in, String charset) throws ParseException, UnsupportedEncodingException {
      return parse(in, ContainerFactory.FACTORY_SIMPLE, ContentHandlerDumy.HANDLER, charset);
   }

	/**
	 * use to return Primitive Type, or String, Or JsonObject or JsonArray
	 * generated by a ContainerFactory
	 * 
	 * NB: This uses the default charset
	 */
	public Object parse(InputStream in, ContainerFactory containerFactory) throws ParseException {
		return parse(in, containerFactory, ContentHandlerDumy.HANDLER);
	}
	
	  /**
    * use to return Primitive Type, or String, Or JsonObject or JsonArray
    * generated by a ContainerFactory
    * 
	 * @throws UnsupportedEncodingException If the named charset is not supported by an InputStreamReader
    */
   public Object parse(InputStream in, ContainerFactory containerFactory, String charset) throws ParseException, UnsupportedEncodingException {
      return parse(in, containerFactory, ContentHandlerDumy.HANDLER, charset);
   }

	/**
	 * use to return Primitive Type, or String, Or JsonObject or JsonArray
	 * generated by a ContainerFactory
	 * 
	 * NB: This uses the default charset
	 */
	public Object parse(InputStream in, ContainerFactory containerFactory, ContentHandler handler)
			throws ParseException {
	   return super.parse(new InputStreamReader(in));
	}
	
	  /**
    * use to return Primitive Type, or String, Or JsonObject or JsonArray
    * generated by a ContainerFactory
    * 
	 * @throws UnsupportedEncodingException If the named charset is not supported by an InputStreamReader
    */
   public Object parse(InputStream in, ContainerFactory containerFactory, ContentHandler handler, String charset)
         throws ParseException, UnsupportedEncodingException {
      return super.parse(new InputStreamReader(in, charset));
   }
}
